### ISSUE TITLE
Parse values from configuration file `.mollie.yaml`

### ISSUE THREAD

**Issue by VictorAvelar** [VictorAvelar/mollie-cli#1]
**Is your feature request related to a problem? Please describe.**
Right now the CLI utility is not able to properly parse the configuration specified in any of the mollie config files.

Example:
When the API token is not passed as flag `mollie profiles current -t=YOUR_TOKEN.
Then the tool will try to fetch it from the environment variable `MOLLIE_API_TOKEN`

Right now if none of the above is set, then all requests fail with status 401.

**Describe the solution you'd like**
When you pass the token using the config file:
```yaml
mollie:
    api_token: test_mollietokenxyz
    mode: test
```
Then the CLI should be able to use it to perform requests.

The hierarchy should be `.mollie.yaml => --token flag => MOLLIE_API_TOKEN env`

**Describe alternatives you've considered**
I would also be in for changing the order of env and token, but for me the one mentioned above makes more sense.

**Additional context**
There is already a viper implementation attempt in place, should try to fix or replace it.

**Comment by ananichev** [comment]
I'll take this one

**Comment by ananichev** [comment]
Hey @VictorAvelar could you please review and check the changes https://github.com/VictorAvelar/mollie-cli/pull/4

**Comment by VictorAvelar** [comment]
I'll have a look 😄.
